version: "3.9"

services:
  # Main Application Database
  postgres:
    image: postgres:15
    container_name: pos-postgres
    restart: always
    env_file:
      - ./pos-db/postgres.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # PGAdmin (DB UI)
  pgadmin:
    image: dpage/pgadmin4
    container_name: pos-pgadmin
    restart: always
    env_file:
      - ./pos-db/pgadmin.env
    ports:
      - "5050:80"
    depends_on:
      - postgres

  # FastAPI Backend
  backend:
    build:
      context: ./pos-backend
      dockerfile: Dockerfile
    container_name: pos-backend
    restart: always
    env_file:
      - ./pos-backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - keycloak
    volumes:
      - ./pos-backend:/app

  # Keycloak Database (SEPARATE)
  keycloak-db:
    image: postgres:15
    container_name: pos-keycloak-db
    restart: always
    env_file:
      - ./pos-idp/keycloak-db.env
    volumes:
      - keycloak_data:/var/lib/postgresql/data

  # Keycloak Server
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.3
    container_name: pos-keycloak
    command: start-dev
    restart: always
    env_file:
      - ./pos-idp/.env
    ports:
      - "8080:8080"
    depends_on:
      - keycloak-db

volumes:
  postgres_data:
  keycloak_data:
