"""add email and nullable customer fields

Revision ID: 087f54139558
Revises: 48e6c9411c05
Create Date: 2026-05-09 17:42:56.597460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '087f54139558'
down_revision: Union[str, Sequence[str], None] = '48e6c9411c05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('email_address', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'customers', ['email_address'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customers', type_='unique')
    op.drop_column('customers', 'email_address')
    # ### end Alembic commands ###
