"""Invoice Table Created | Separate Items Table

Revision ID: 55d2a29840fd
Revises: 087f54139558
Create Date: 2026-05-09 21:07:05.022497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55d2a29840fd'
down_revision: Union[str, Sequence[str], None] = '087f54139558'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoices',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=True),
    sa.Column('cashier_id', sa.String(), nullable=False),
    sa.Column('customer_phone_number', sa.String(), nullable=True),
    sa.Column('customer_email_address', sa.String(), nullable=True),
    sa.Column('edible_total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('sellable_total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('loyalty_points_used', sa.Integer(), nullable=True),
    sa.Column('edible_discount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('sellable_discount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('invoice_discount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('manual_discount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('gst_charge', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('outlet_charge', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('order_type', sa.String(), nullable=True),
    sa.Column('grand_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(), nullable=True),
    sa.Column('txn_receipt', sa.String(), nullable=True),
    sa.Column('store_id', sa.String(), nullable=True),
    sa.Column('store_name', sa.String(), nullable=True),
    sa.Column('store_location', sa.String(), nullable=True),
    sa.Column('table_number', sa.String(), nullable=True),
    sa.Column('invoice_date_and_time', sa.DateTime(), nullable=True),
    sa.Column('receipt_path', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['cashier_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoice_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('invoice_id', sa.String(), nullable=True),
    sa.Column('resource_id', sa.String(), nullable=True),
    sa.Column('item_name', sa.String(), nullable=True),
    sa.Column('item_type', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoice_items')
    op.drop_table('invoices')
    # ### end Alembic commands ###
